# Generate edh_embedded_resources.{h,cpp} from resources/ (run via: cmake -P).
# -DEDH_RES_DIR=...  source folder containing default.cfg, embed.json, embed_EN.json, embed_NL.json, …
# -DEDH_OUT_DIR=...  output folder for generated files
if(NOT DEFINED EDH_RES_DIR OR NOT DEFINED EDH_OUT_DIR)
	message(FATAL_ERROR "edh_gen_embedded.cmake: set EDH_RES_DIR and EDH_OUT_DIR")
endif()

set(_files
	default.cfg
	embed.json
	embed_EN.json
	embed_NL.json
)
set(_symbols
	edh_embed_default_cfg
	edh_embed_embed_json
	edh_embed_embed_en_json
	edh_embed_embed_nl_json
)

set(H "// Generated by cmake/edh_gen_embedded.cmake — do not edit.\n#pragma once\n#include <stddef.h>\n\n")
set(CPP "// Generated by cmake/edh_gen_embedded.cmake — do not edit.\n#include \"edh_embedded_resources.h\"\n\n")

set(_idx 0)
foreach(_fname IN LISTS _files)
	list(GET _symbols ${_idx} _sym)
	math(EXPR _idx "${_idx}+1")

	set(_path "${EDH_RES_DIR}/${_fname}")
	if(NOT EXISTS "${_path}")
		message(FATAL_ERROR "edh_gen_embedded.cmake: missing ${_path}")
	endif()
	file(READ "${_path}" _hex HEX)
	string(LENGTH "${_hex}" _hexlen)
	if(_hexlen EQUAL 0)
		message(FATAL_ERROR "edh_gen_embedded.cmake: empty file ${_path}")
	endif()

	string(APPEND H "extern const unsigned char ${_sym}[];\n")
	string(APPEND H "extern const size_t ${_sym}_size;\n\n")

	set(_bytes "")
	math(EXPR _last "${_hexlen}-2")
	foreach(i RANGE 0 ${_last} 2)
		string(SUBSTRING "${_hex}" ${i} 2 _byte)
		list(APPEND _bytes "0x${_byte}")
	endforeach()
	string(REPLACE ";" ", " _body "${_bytes}")

	string(APPEND CPP "const unsigned char ${_sym}[] = { ${_body} };\n")
	string(APPEND CPP "const size_t ${_sym}_size = sizeof(${_sym});\n\n")
endforeach()

file(MAKE_DIRECTORY "${EDH_OUT_DIR}")
file(WRITE "${EDH_OUT_DIR}/edh_embedded_resources.h" "${H}")
file(WRITE "${EDH_OUT_DIR}/edh_embedded_resources.cpp" "${CPP}")
